# Generated by Django 4.2.5 on 2023-11-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websiteapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="gallery/")),
            ],
        ),
    ]
