# Generated by Django 4.2.5 on 2023-11-01 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("websiteapp", "0002_galleryimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.DeleteModel(
            name="WorkExperience",
        ),
    ]
